### ISSUE TITLE
Design Open Data Checklist

### ISSUE THREAD

**Issue by stephwright** [stephwright/Brain#16]
- [x] Create content: https://public.etherpad-mozilla.org/p/opendata-checklist
- [x] Add to @auremoser checklist template: http://auremoser.github.io/checklist/
- [x] Review by team on first March team call
- [x] Present to cmty on 3/10 cmty call
- [x] Revise based on feedback
- [x] Send out to the world

**Comment by auremoser** [comment]
I can help with this if you need anything fancy! Just ping me when you're read content-wise and i'll add you to the repo etcet.

**Comment by stephwright** [comment]
Thanks, @auremoser !  Will do.
