### ISSUE TITLE
Final prep checklist for Global Sprint

### ISSUE THREAD

**Issue by stephwright** [stephwright/Brain#31]
- [x] Set up A/V test time w/ Karla & Arliss & me
- [x] Check food ordered
- [x] Send reminder email to participants registered
- [x] Send reminder to co-leads
- [ ] Send reminder to featured project speakers
- [x] check DSS laptop reserved for me
- [x] check wifi set up
- [x] bring swag
- [x] bring promotion materials for MSL Fellows cohort
